# Generated by Django 3.2.8 on 2021-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
